class CapitalCityApi {
  static int chosenPresetLength = 777; //doesnt matter what value as it overwritten from loadPreset function

  static List<String> allCountries = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas",
    "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana",
    "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad",
    "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia", "Denmark", "Djibouti",
    "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland",
    "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea Bissau", "Guyana",
    "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan",
    "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
    "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia",
    "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger",
    "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
    "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal",
    "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan",
    "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand",
    "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
    "Uruguay", "Uzbekistan", "Vanuatu", "Vatican", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
  ];

  static List<String> chosenPreset = [
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas",
    "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana",
    "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad",
    "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia", "Denmark", "Djibouti",
    "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland",
    "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea Bissau", "Guyana",
    "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan",
    "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
    "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia",
    "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger",
    "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
    "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal",
    "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan",
    "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand",
    "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
    "Uruguay", "Uzbekistan", "Vanuatu", "Vatican", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
  ];
  
  static List<String> europePreset = [
    "Albania", "Andorra", "Armenia", "Austria", "Azerbaijan", "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Cyprus", "Czechia",
    "Denmark", "Estonia", "Finland", "France", "Georgia", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Kazakhstan", "Kosovo", "Latvia",
    "Liechtenstein", "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal", "Romania",
    "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "Turkey", "Ukraine", "United Kingdom", "Vatican"
  ];

  static List<String> africaPreset = [
    "Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Republic", "Chad", "Comoros", "Congo", "Democratic Republic of the Congo",
    "Djibouti", "Egypt", "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Ivory Coast", "Kenya", "Lesotho", "Liberia",
    "Libya", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal",
    "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Tanzania", "Togo", "Tunisia", "Uganda", "Zambia", "Zimbabwe"
  ];

  static List<String> asiaPreset = [
    "Afghanistan", "Armenia", "Azerbaijan", "Bahrain", "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China", "Cyprus", "Georgia", "India", "Indonesia", "Iran",
    "Iraq", "Israel", "Japan", "Jordan", "Kazakhstan", "Kuwait", "Kyrgyzstan", "Laos", "Lebanon", "Malaysia", "Maldives", "Mongolia", "Myanmar", "Nepal", "North Korea",
    "Oman", "Pakistan", "Palestine", "Philippines", "Qatar", "Russia", "Saudi Arabia", "Singapore", "South Korea", "Sri Lanka", "Syria", "Taiwan", "Tajikistan", "Thailand",
    "Timor-Leste", "Turkey", "Turkmenistan", "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen"
  ];

  static List<String> northAmericaPreset = [
    "Antigua and Barbuda", "Bahamas", "Barbados", "Belize", "Canada", "Costa Rica", "Cuba", "Dominica", "Dominican Republic", "El Salvador", "Grenada", "Guatemala",
    "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Trinidad and Tobago", "United States"
  ];


  static List<String> southAmericaPreset = [
    "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay", "Venezuela"
  ];

  static List<String> oceaniaPreset = [
    "Australia", "Fiji", "Kiribati", "Marshall Islands", "Micronesia", "Nauru", "New Zealand", "Palau", "Papua New Guinea", "Samoa", "Solomon Islands", "Tonga",
    "Tuvalu", "Vanuatu"
  ];

  /// Returns the capital city from the country name
  static String? getCapitalFromName(String countryName) {
    Map<String, String> capitalsMap = {
      "Afghanistan": "Kabul",
      "Albania": "Tirana",
      "Algeria": "Algiers",
      "Andorra": "Andorra la Vella",
      "Angola": "Luanda",
      "Antigua and Barbuda": "St. John's",
      "Argentina": "Buenos Aires",
      "Armenia": "Yerevan",
      "Australia": "Canberra",
      "Austria": "Vienna",
      "Azerbaijan": "Baku",
      "Bahamas": "Nassau",
      "Bahrain": "Manama",
      "Bangladesh": "Dhaka",
      "Barbados": "Bridgetown",
      "Belarus": "Minsk",
      "Belgium": "Brussels",
      "Belize": "Belmopan",
      "Benin": "Porto-Novo",
      "Bhutan": "Thimphu",
      "Bolivia": "Sucre",
      "Bosnia and Herzegovina": "Sarajevo",
      "Botswana": "Gaborone",
      "Brazil": "Brasília",
      "Brunei": "Bandar Seri Begawan",
      "Bulgaria": "Sofia",
      "Burkina Faso": "Ouagadougou",
      "Burundi": "Gitega",
      "Cabo Verde": "Praia",
      "Cambodia": "Phnom Penh",
      "Cameroon": "Yaoundé",
      "Canada": "Ottawa",
      "Central African Republic": "Bangui",
      "Chad": "N'Djamena",
      "Chile": "Santiago",
      "China": "Beijing",
      "Colombia": "Bogotá",
      "Comoros": "Moroni",
      "Congo": "Brazzaville",
      "Costa Rica": "San José",
      "Croatia": "Zagreb",
      "Cuba": "Havana",
      "Cyprus": "Nicosia",
      "Czechia": "Prague",
      "Denmark": "Copenhagen",
      "Djibouti": "Djibouti City",
      "Dominica": "Roseau",
      "Dominican Republic": "Santo Domingo",
      "Ecuador": "Quito",
      "Egypt": "Cairo",
      "El Salvador": "San Salvador",
      "Equatorial Guinea": "Malabo",
      "Eritrea": "Asmara",
      "Estonia": "Tallinn",
      "Eswatini": "Mbabane",
      "Ethiopia": "Addis Ababa",
      "Fiji": "Suva",
      "Finland": "Helsinki",
      "France": "Paris",
      "Gabon": "Libreville",
      "Gambia": "Banjul",
      "Georgia": "Tbilisi",
      "Germany": "Berlin",
      "Ghana": "Accra",
      "Greece": "Athens",
      "Grenada": "St. George's",
      "Guatemala": "Guatemala City",
      "Guinea": "Conakry",
      "Guinea Bissau": "Bissau",
      "Guyana": "Georgetown",
      "Haiti": "Port-au-Prince",
      "Honduras": "Tegucigalpa",
      "Hungary": "Budapest",
      "Iceland": "Reykjavik",
      "India": "New Delhi",
      "Indonesia": "Jakarta",
      "Iran": "Tehran",
      "Iraq": "Baghdad",
      "Ireland": "Dublin",
      "Israel": "Jerusalem",
      "Italy": "Rome",
      "Jamaica": "Kingston",
      "Japan": "Tokyo",
      "Jordan": "Amman",
      "Kazakhstan": "Nur-Sultan",
      "Kenya": "Nairobi",
      "Kiribati": "South Tarawa",
      "Kosovo": "Pristina",
      "Kuwait": "Kuwait City",
      "Kyrgyzstan": "Bishkek",
      "Laos": "Vientiane",
      "Latvia": "Riga",
      "Lebanon": "Beirut",
      "Lesotho": "Maseru",
      "Liberia": "Monrovia",
      "Libya": "Tripoli",
      "Liechtenstein": "Vaduz",
      "Lithuania": "Vilnius",
      "Luxembourg": "Luxembourg",
      "Madagascar": "Antananarivo",
      "Malawi": "Lilongwe",
      "Malaysia": "Kuala Lumpur",
      "Maldives": "Malé",
      "Mali": "Bamako",
      "Malta": "Valletta",
      "Marshall Islands": "Majuro",
      "Mauritania": "Nouakchott",
      "Mauritius": "Port Louis",
      "Mexico": "Mexico City",
      "Micronesia": "Palikir",
      "Moldova": "Chișinău",
      "Monaco": "Monaco",
      "Mongolia": "Ulaanbaatar",
      "Montenegro": "Podgorica",
      "Morocco": "Rabat",
      "Mozambique": "Maputo",
      "Myanmar": "Naypyidaw",
      "Namibia": "Windhoek",
      "Nauru": "Yaren",
      "Nepal": "Kathmandu",
      "Netherlands": "Amsterdam",
      "New Zealand": "Wellington",
      "Nicaragua": "Managua",
      "Niger": "Niamey",
      "Nigeria": "Abuja",
      "North Korea": "Pyongyang",
      "North Macedonia": "Skopje",
      "Norway": "Oslo",
      "Oman": "Muscat",
      "Pakistan": "Islamabad",
      "Palau": "Ngerulmud",
      "Panama": "Panama City",
      "Papua New Guinea": "Port Moresby",
      "Paraguay": "Asunción",
      "Peru": "Lima",
      "Philippines": "Manila",
      "Poland": "Warsaw",
      "Portugal": "Lisbon",
      "Qatar": "Doha",
      "Romania": "Bucharest",
      "Russia": "Moscow",
      "Rwanda": "Kigali",
      "Saint Kitts and Nevis": "Basseterre",
      "Saint Lucia": "Castries",
      "Saint Vincent and the Grenadines": "Kingstown",
      "Samoa": "Apia",
      "San Marino": "San Marino",
      "Sao Tome and Principe": "São Tomé",
      "Saudi Arabia": "Riyadh",
      "Senegal": "Dakar",
      "Serbia": "Belgrade",
      "Seychelles": "Victoria",
      "Sierra Leone": "Freetown",
      "Singapore": "Singapore",
      "Slovakia": "Bratislava",
      "Slovenia": "Ljubljana",
      "Solomon Islands": "Honiara",
      "Somalia": "Mogadishu",
      "South Africa": "Pretoria",
      "South Korea": "Seoul",
      "South Sudan": "Juba",
      "Spain": "Madrid",
      "Sri Lanka": "Colombo",
      "Sudan": "Khartoum",
      "Suriname": "Paramaribo",
      "Sweden": "Stockholm",
      "Switzerland": "Bern",
      "Syria": "Damascus",
      "Taiwan": "Taipei",
      "Tajikistan": "Dushanbe",
      "Tanzania": "Dodoma",
      "Thailand": "Bangkok",
      "Timor-Leste": "Dili",
      "Togo": "Lomé",
      "Tonga": "Nuku'alofa",
      "Trinidad and Tobago": "Port of Spain",
      "Tunisia": "Tunis",
      "Turkey": "Ankara",
      "Turkmenistan": "Ashgabat",
      "Tuvalu": "Funafuti",
      "Uganda": "Kampala",
      "Ukraine": "Kyiv",
      "United Arab Emirates": "Abu Dhabi",
      "United Kingdom": "London",
      "United States": "Washington DC", // Washington, D.C.
      "Uruguay": "Montevideo",
      "Uzbekistan": "Tashkent",
      "Vanuatu": "Port Vila",
      "Vatican": "Vatican City",
      "Venezuela": "Caracas",
      "Vietnam": "Hanoi",
      "Yemen": "Sana'a",
      "Zambia": "Lusaka",
      "Zimbabwe": "Harare"
    };
    
    return capitalsMap[countryName];
  }

  /// Sets the chosen preset
  static void loadPreset(List<String> presetChosen) {
    CapitalCityApi.chosenPreset = presetChosen.toList();
    CapitalCityApi.chosenPresetLength = presetChosen.length;
  }
}